[package]
name = "six"
version = "0.1.0"
authors = ["陈浩银 <chen.haoyin@angsivip.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
